### PR TITLE
Cache contexts on 404

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Comment by attiks** [comment]
```
The process "cd html/themes/custom/common_design_subtheme && npm install" e  
  xceeded the timeout of 300 seconds. 
```

**Comment by attiks** [comment]
More info

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

**Comment by lazysoundsystem** [comment]
Fix tests with solution borrowed from https://github.com/UN-OCHA/gho-2022-site/pull/87/commits/73b62fadd2b793c8f7bb063e5fe0eb78de38d9e2

**Comment by lazysoundsystem** [comment]
Failed this time as git.drupalcode.org is down - will try again when it's back.

image

**Review by lazysoundsystem — APPROVED** [review]

**Pull request merged**
